spring.application.name=quiz-tutor

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quiz_tutor_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Drivers

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}

groq.api.key=${GROQ_API_KEY}

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

jwt.secret=${JWT_SECRET:miClaveSecretaSuperSegura123Quiz2026}