spring.application.name=quiz-tutor

# Base de datos (Usa la variable de entorno, si no existe usa localhost)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quiz_tutor_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto (Railway inyecta el puerto automáticamente en la variable PORT)
server.port=${PORT:8080}

# APIs y Seguridad
groq.api.key=${GROQ_API_KEY}
jwt.secret=${JWT_SECRET:miClaveSecretaSuperSegura123Quiz2026s}

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true